name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "check out master"
      uses: actions/checkout@v3
    - name: "move to directory"
      run: "cd lecture/lecture3-4 && make test && ./test" 

