# name: C/C++ CI

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - name: "check out master"
#       uses: actions/checkout@v3
#     - name: "move to directory"
#       run: "cd pe/pe3_references && make test && ./test" 

